### ISSUE TITLE
fuzztesting & licensing

### ISSUE THREAD

**Issue by jamen** [scrapjs/contributing#5]
It would be interesting to use a whole bunch of limbo js repos for fuzztesting purposes, e.g. testing reliability of tools/parsers/etc. on a few userland packages, even if there is errors in a few (might be better :stuck_out_tongue:)

One question I have is with licensing.  Should packages transferred here just maintain their licenses, or should they be relicensed to MIT or public domain?  I'm not sure what the process of doing that is, though.  Maybe some agreement required between collaborators before transferring.

**Comment by dy** [comment]
Oh that is important question! I think transfering license to public domain is important step, and I guess only the author can do that, but we need some legal consultation to be sure.

**Comment by jamen** [comment]
So I found [Unlicense](http://unlicense.org/) which seems to be a good solution.  

Create PRs that:

 1. Delete `LICENSE`
 2. Create `UNLICENSE` with public domain statement
 3. Ping major contributors to [add their statements](http://unlicense.org/#unlicensing-contributions) (like an unlicense CLA)

If you are the sole contributor I think it's safe to say you can skip the PR and step 3.

**Comment by dy** [comment]
@jamen yes, it has nice copyright symbol <img src="http://upload.wikimedia.org/wikipedia/commons/6/62/PD-icon.svg" width="20"/> (which can be put with badges or at the end of readme), also this scrapjs is probably the best case for that.

I used it for a while, but the problem is that it is not considered as a legal license in some countries, like Germany, and therefore falls back to default pretty strict license, which is far from MIT. Not sure though the status-quo.

**Comment by jamen** [comment]
Licensing seems harder to manage now that we have around 150 scrap repos.  So what I did is [created archives](https://github.com/jamen/archives) and released them to public domain, while transferring some the original repos here.
